config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :properties do
    resources :appointments, only: %i[show new create]
  end

  devise_for :agents
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/agent.rb
# frozen_string_literal: true

class Agent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :rememberable

  has_many :properties
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(_auth_object = nil)
    authorizable_ransackable_attributes
  end

  def self.ransackable_associations(_auth_object = nil)
    authorizable_ransackable_associations
  end
end

app/models/appointment.rb
# frozen_string_literal: true

class Appointment < ApplicationRecord
  belongs_to :property
  belongs_to :agent
end

app/models/property.rb
# frozen_string_literal: true

class Property < ApplicationRecord
  belongs_to :agent
  has_many :appointments
  validates :location, :area, :variant, :size, :caption, presence: true

  validates :size, comparison: { greater_than: 0 }

  VALID_VARIANTS = %w[Flat Land].freeze
  validates :variant, inclusion: { in: VALID_VARIANTS }

  VALID_STATUSES = %w[Available Private Locked Sold].freeze
  validates :status, inclusion: { in: VALID_STATUSES }

  has_many_attached :images do |attachable|
    attachable.variant :sm, resize_to_limit: [300, 300], preprocessed: true
  end

  scope :flat, -> { where(variant: 'Flat') }
  scope :land, -> { where(variant: 'Land') }

  scope :available, -> { where(status: 'Available') }
  scope :locked, -> { where(status: 'Locked') }
  scope :private_, -> { where(status: 'Private') }
  scope :sold, -> { where(status: 'Sold') }

  scope :filter_by_variant, ->(variant) { where variant: }
  scope :filter_by_caption, ->(caption) { where 'property.caption ILIKE ?', "%#{caption}%" }
  scope :order_by, ->(attribute) { order("properties.#{attribute} ASC") }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
# frozen_string_literal: true

class AppointmentsController < InheritedResources::Base
  def new
    @property = Property.find(params[:property_id])
    @appointment = @property.appointments.new
  end

  def create; end
  
  private

  def appointment_params
    params.require(:appointment).permit(:property_id, :agent_id, :date,
                                        :client_name, :client_address, :time_slot,
                                        :client_phone_number, :addtional_query)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end
end

app/controllers/properties_controller.rb
# frozen_string_literal: true

class PropertiesController < ApplicationController
  before_action :set_property, only: %i[show edit update destroy]
  before_action :authenticate_agent!, only: %i[new create edit update destroy]

  def index
    @properties = Property.available

    if params[:variant].present? && params[:variant] != 'All'
      @properties = @properties.filter_by_variant(params[:variant])
      @selected_variant = params[:variant]
    end

    if params[:order_by].present? && params[:order_by] != 'default'
      @properties = @properties.order_by(params[:order_by])
      @selected_order = params[:order_by]
    end

    @properties = @properties.filter_by_caption(params[:caption]) if params[:caption].present?
  end

  def show
    @agent = @property.agent
  end

  def new
    @property = Property.new
  end

  def edit; end

  def create
    @property = Property.new(property_params)

    if @property.save
      redirect_to property_url(@property), notice: 'Property was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @property.agent.id != current_agent.id
      redirect_to property_url(@property), notice: 'You are not permitted to edit this property.'
    end

    if @property.update(property_params)
      redirect_to property_url(@property), notice: 'Property was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @property.destroy!

    redirect_to properties_url, notice: 'Property was successfully destroyed.'
  end

  private

  def set_property
    @property = Property.find(params[:id])
  end

  def property_params
    params.require(:property).permit(:caption, :area, :location, :variant, :status, :description, :size, :agent_id,
                                     images: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/appointments/_appointment.html.erb
<div id="<%= dom_id appointment %>">
  <p>
    <strong>Property:</strong>
    <%= appointment.property_id %>
  </p>

  <p>
    <strong>Agent:</strong>
    <%= appointment.agent_id %>
  </p>

  <p>
    <strong>Date:</strong>
    <%= appointment.date %>
  </p>

  <p>
    <strong>Client name:</strong>
    <%= appointment.client_name %>
  </p>

  <p>
    <strong>Client address:</strong>
    <%= appointment.client_address %>
  </p>

  <p>
    <strong>Time slot:</strong>
    <%= appointment.time_slot %>
  </p>

  <p>
    <strong>Client phone number:</strong>
    <%= appointment.client_phone_number %>
  </p>

  <p>
    <strong>Addtional query:</strong>
    <%= appointment.addtional_query %>
  </p>

</div>

app/views/appointments/new.html.erb
<div class="card w-full max-w-xl shadow-xl mx-auto md:p-5">
	<h2 class="text-3xl py-3">Create a new Appointment</h2>
	<%= form_for [@property, @appointment] do |form| %>
		
		<%= form.hidden_field :property_id, value: @property.id %>
		<%= form.hidden_field :agent_id, value: @property.agent.id %>

		<div class="form-control">
			<label class="label">
				<span class="label-text">Select a date</span>
			</label>
			<input type="date" class="bg-base-100 border border-primary text-sm rounded-lg focus:ring-primary cursor-pointer w-1/2 p-2.5" required>
		</div>

		<div class="form-control">
			<label class="label">
				<span class="label-text">Your Name</span>
			</label>
			<%= form.text_field :client_name, class: "input input-bordered input-primary w-full max-w-sm", placeholder: "Your Name"%>
			<% @appointment.errors.full_messages_for(:client_name).each do |message| %>
				<p class="text-xs text-red-500"><%= message %></p>
			<% end %>
		</div>

		<div class="form-control">
			<label class="label">
				<span class="label-text">Your Address</span>
			</label>
			<%= form.text_field :client_address, class: "input input-bordered input-primary w-full max-w-sm", placeholder: "Your Address"%>
			<% @appointment.errors.full_messages_for(:client_address).each do |message| %>
				<p class="text-xs text-red-500"><%= message %></p>
			<% end %>
		</div>

		<div class="form-control">
			<label class="label">
				<%= form.label :time_slot, class: "label-text" %>
			</label>
			<%= form.text_field :time_slot, class: "input input-bordered input-primary w-full max-w-sm", placeholder: "Time Slot"%>
			<% @appointment.errors.full_messages_for(:time_slot).each do |message| %>
				<p class="text-xs text-red-500"><%= message %></p>
			<% end %>
		</div>

		<div class="form-control">
			<label class="label">
				<span class="label-text">Your phone number</span>
			</label>
			<%= form.telephone_field :client_phone_number, class: "input input-bordered input-primary w-full max-w-sm", placeholder: "Your phone number"%>
			<% @appointment.errors.full_messages_for(:client_phone_number).each do |message| %>
				<p class="text-xs text-red-500"><%= message %></p>
			<% end %>
		</div>

		<div class="form-control">
			<label class="label">
				<%= form.label :addtional_query, class: "label-text" %>
			</label>
			<%= form.text_area :addtional_query, class: "textarea textarea-primary max-w-sm" %>
			<% @appointment.errors.full_messages_for(:addtional_query).each do |message| %>
				<p class="text-xs text-red-500"><%= message %></p>
			<% end %>
		</div>

		<div class="form-control mt-6">
			<%= form.submit "Create Appointment", class: "btn btn-accent" %>
		</div>
	<% end %>
</div>

app/views/appointments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @appointment %>

<div>
  <%= link_to "Edit this appointment", edit_appointment_path(@appointment) %> |
  <%= link_to "Back to appointments", appointments_path %>

  <%= button_to "Destroy this appointment", @appointment, method: :delete %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer mt-10 p-10 bg-base-200 text-base-content">
  <aside>
    <svg width="50" height="50" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" class="fill-current"><path d="M22.672 15.226l-2.432.811.841 2.515c.33 1.019-.209 2.127-1.23 2.456-1.15.325-2.148-.321-2.463-1.226l-.84-2.518-5.013 1.677.84 2.517c.391 1.203-.434 2.542-1.831 2.542-.88 0-1.601-.564-1.86-1.314l-.842-2.516-2.431.809c-1.135.328-2.145-.317-2.463-1.229-.329-1.018.211-2.127 1.231-2.456l2.432-.809-1.621-4.823-2.432.808c-1.355.384-2.558-.59-2.558-1.839 0-.817.509-1.582 1.327-1.846l2.433-.809-.842-2.515c-.33-1.02.211-2.129 1.232-2.458 1.02-.329 2.13.209 2.461 1.229l.842 2.515 5.011-1.677-.839-2.517c-.403-1.238.484-2.553 1.843-2.553.819 0 1.585.509 1.85 1.326l.841 2.517 2.431-.81c1.02-.33 2.131.211 2.461 1.229.332 1.018-.21 2.126-1.23 2.456l-2.433.809 1.622 4.823 2.433-.809c1.242-.401 2.557.484 2.557 1.838 0 .819-.51 1.583-1.328 1.847m-8.992-6.428l-5.01 1.675 1.619 4.828 5.011-1.674-1.62-4.829z"></path></svg>
    <p>&copy; 2024 Amar-Jomi. Full rights reserved<br>Your trustworthy Property Vendor.</p>
		<p>Are you an agent? <%= link_to "Sign in", new_agent_session_path, class: "link link-primary" %></p>
  </aside> 
  <nav>
    <form>
    <h6 class="footer-title">Newsletter</h6> 
    <fieldset class="form-control w-80">
      <label class="label">
        <span class="label-text">Enter your email address</span>
      </label> 
      <div class="join">
        <input type="text" placeholder="username@site.com" class="input input-bordered join-item" /> 
        <button class="btn btn-info join-item">Subscribe</button>
      </div>
    </fieldset>
  </form>
  </nav>
</footer>

app/views/layouts/_navbar.html.erb
<div class="navbar glass">
  <div class="flex-1">
    <a href="/" class="btn btn-ghost text-xl">
			<img src="/assets/logo.png" class="h-10" alt="Amar-Jomi Logo" />
			<span class="font-raleway font-bold italic">Amar-Jomi</span>
		</a>
  </div>
  <div class="flex-none">
    <ul class="menu menu-horizontal px-1">
			<li>
				<%= link_to "Properties", properties_path %>
			</li>
			<% if agent_signed_in? %>
				<li>
					<details>
						<summary>
							<%= current_agent.name %>
						</summary>
						<ul class="p-2 bg-base-100 rounded-t-none">
							<li>
								<%= link_to "Profile", "#" %>
							</li>
							<li>
								<%= button_to "Logout", destroy_agent_session_path, method: :delete  %>
							</li>
						</ul>
					</details>
				</li>
			<% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html data-theme="lemonade">
  <head>
    <title>AmarJomi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body class="min-h-screen flex flex-col justify-between font-raleway bg-[url('vector_bg_abstract.jpg')] bg-fixed">
		<div>
      <%= render "layouts/navbar" %>
			<%= render "shared/flash" %>
      <main>
        <%= yield %>
      </main>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/properties/_filter_bar.html.erb
<div class="p-3 rounded-lg m-10 md:w-8/12 mt-5 md:mt-10 w-11/12 mx-auto items-center bg-base-200">
	<%= form_with url: properties_path, method: :get do |form| %>
		<div class="flex justify-start md:gap-4 gap-2 items-center">
			<div class="form-control w-20 md:w-24">
				<label class="label" for="variant">
					<span class="label-text">Variant</span>
				</label>
				<select name="variant" class="select select-bordered select-sm">
					<option value="All">All</option>
					<option value="Land" <%= "selected" if @selected_variant == "Land" %>>Land</option>
					<option value="Flat" <%= "selected" if @selected_variant == "Flat" %>>Flat</option>
				</select>
			</div>
			<div class="form-control w-24">
				<label class="label" for="area">
					<span class="label-text">Area</span>
				</label>
				<select name="area" class="select select-bordered select-sm">
					<option value="All">All</option>
					<option value="Mirpur">Mirpur</option>
					<option value="Uttara">Uttara</option>
					<option value="Kuril">Kuril</option>
				</select>
			</div>

			<div class="form-control w-24 md:w-24">
				<label class="label" for="order_by">
					<span class="label-text">Sort by</span>
				</label>
				<select name="order_by" class="select select-bordered select-sm">
					<option value="default"<%= "selected" if @selected_order == "default" %>>Default</option>
					<option value="created_at" <%= "selected" if @selected_order == "created_at" %>>Newest</option>
					<option value="price"<%= "selected" if @selected_order == "price" %>>Price</option>
					<option value="popularity"<%= "selected" if @selected_order == "popularity" %>>Popularity</option>
				</select>

			</div>

			<div class="form-control">
				<label class="label" for="submit">
					<span class="label-text">&nbsp;</span>
				</label>
				<%= form.submit "Filter", class: "btn btn-secondary btn-sm" %>
			</div>
			
		</div>
	<% end %>
</div>

app/views/properties/_form.html.erb
<%= form_with(model: property, html: { data: { controller: "form" } }) do |form| %>
  <%= form.hidden_field :agent_id, value: current_agent.id %>

  <div class="form-control mt-2">
    <label class="label">
      <%= form.label :images, class: "label-text" %>
    </label>
    <%= form.file_field :images, multiple: true, accept: 'image/png,image/jpeg', class: "file-input file-input-bordered w-full max-w-xs" %>
  </div> 

	<div class="form-control">
    <label class="label">
		  <%= form.label :caption, class: "label-text" %>
    </label>
		<%= form.text_field :caption, class: "input input-bordered input-primary w-full max-w-sm", placeholder: "Caption"%>
    <% property.errors.full_messages_for(:caption).each do |message| %>
      <p class="text-xs text-red-500"><%= message %></p>
    <% end %>
	</div>

  <div class="flex flex-col md:flex-row md:space-x-3">
    <div class="form-control">
      <label class="label">
        <%= form.label :area, class: "label-text" %>
      </label>
      <%= form.text_field :area, class: "input input-bordered input-primary w-full max-w-sm", placeholder: "Area" %>
      <% property.errors.full_messages_for(:area).each do |message| %>
        <p class="text-xs text-red-500"><%= message %></p>
      <% end %>
    </div>
    <div class="form-control">
      <label class="label">
        <%= form.label :location, class: "label-text" %>
      </label>
      <%= form.text_field :location, class: "input input-bordered input-primary max-w-sm", placeholder: "Location"%>
      <% property.errors.full_messages_for(:location).each do |message| %>
        <p class="text-xs text-red-500"><%= message %></p>
      <% end %>
    </div>
  </div>

  <div class="flex flex-col md:flex-row md:space-x-3">
    <div class="form-control">
      <label class="label">
        <%= form.label :variant, class: "label-text" %>
      </label>
      <%= form.select :variant, Property::VALID_VARIANTS, {}, class: "select select-primary w-full max-w-sm", data: { "form-target": "variant", action: "change->form#updateUnit" } %>
    </div>
    <div class="form-control">
      <label class="label">
        <%= form.label :size, class: "label-text", data: { "form-target": "sizelabel"} %>
      </label>
      <%= form.number_field :size, class: "input input-bordered input-primary w-full max-w-sm join-item", data: { "form-target": "sizeinput" } %>
      <% property.errors.full_messages_for(:size).each do |message| %>
        <p class="text-xs text-red-500"><%= message %></p>
      <% end %>
    </div>
  </div>

  <div class="form-control md:w-1/3">
    <label class="label">
      <%= form.label :status, class: "label-text" %>
    </label>
    <%= form.select :status, Property::VALID_STATUSES, {}, class: "select select-primary w-full max-w-sm" %>
  </div>

  <div class="form-control">
    <label class="label">
      <%= form.label :description, class: "label-text" %>
    </label>
    <%= form.text_area :description, class: "textarea textarea-primary max-w-sm" %>
    <% property.errors.full_messages_for(:description).each do |message| %>
      <p class="text-xs text-red-500"><%= message %></p>
    <% end %>
  </div>
 
  <div class="form-control mt-6">
    <%= form.submit "Create Property", class: "btn btn-accent" %>
  </div>
<% end %>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>">
	<div class="card md:w-56 w-8/10 h-[300px] md:h-[450px] glass mx-auto">
		<figure class="h-2/5">
			<% if property.images.attached? %>
				<%= image_tag property.images.first, alt: "property image", class: "md:h-48 object-fill" %>
			<% else %>
				<% if property.variant == "Land" %>
					<%=  render "shared/land_alternative" %>
				<% else %>
					<%= render "shared/flat_alternative" %>
				<% end %>
			<% end %>
		</figure>
		<div class="card-body">
			<h2 class="card-title"><%= property.caption.truncate(25) %></h2>
			<p><%= property.description.truncate(60) %></p>
			<div class="card-actions justify-start">
				<div class="badge badge-outline"><%= property.variant %></div>
				<div class="badge badge-outline"><%= property.area %></div>
			</div>
		</div>
	</div>
</div>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Show this property", @property %> |
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/index.html.erb
<%= render "filter_bar" %>
<div id="properties" class="grid grid-cols-1 mt-3 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 2xl:grid-cols-5 mx-auto w-11/12 md:w-8/12 gap-3 bordered">
  <% @properties.each do |property| %>
    <%= link_to property do %>
			<%= render property %>
		<% end %>
  <% end %>
</div>

app/views/properties/new.html.erb
<div class="mx-auto p-5">
  <%= link_to properties_path, class: "btn" do %>
  &larr; Back to properties
  <% end %>

  <div class="card w-full max-w-xl shadow-xl mx-auto md:p-5">
    <h2 class="text-3xl py-3">Create a new property</h2>

    <%= render "form", property: @property %>
  </div>
</div>

app/views/properties/show.html.erb
<section class="py-12 sm:py-16"> 
	<div class="container mx-auto px-4 grid grid-cols-1 lg:grid-cols-2 gap-4">
		<!-- Carousel Start -->
		<div class="glass p-3">
			<% if @property.images.attached? %>
				<div class="carousel">
					<% @property.images.each_with_index do |image, i| %>
						<div id="image<%= i+1 %>" class="carousel-item h-96 w-full">
							<%= image_tag image, class: "w-full" %>
						</div>
					<% end %>
				</div>
				<div class="flex justify-center w-full py-2 gap-2">
					<% for i in 0...@property.images.length %>
						<a href="#image<%= i+1 %>" class="btn btn-xs" data-turbo="false"><%= i+1 %></a>
					<% end %>
				</div>
			<% else %>
				<div class="mx-auto w-9/12">
					<%= render "shared/no_image" %>
				</div>
			<% end %>
		</div>
		<!-- Carousel End -->
		
		<div>
			<div>
				<h1 class="text-4xl font-bold"><%= @property.caption %>!</h1>
				<dl class="sm:divide-y sm:divide-gray-200">
          <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-gray-500">
							Type
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
							<%= @property.variant %>
            </dd>
          </div>
          <div class="py-2 sm:py-3 2xl:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-gray-500">
							Location
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
							<%= @property.location %>
            </dd>
          </div>
          <div class="py-2 sm:py-3 2xl:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-gray-500">
							Area
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
							<%= @property.area %>
            </dd>
          </div>
          <div class="py-2 sm:py-3 2xl:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
            <dt class="text-sm font-medium text-gray-500">
							Size
            </dt>
            <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
							<%= @property.size %>
							<span class="text-semibold text-gray-600 ml-3">
								<%= @property.variant == "Land" ? "Katha" : "Square Feet" %>
							</span>
            </dd>
          </div>
				</dl>
				<p class="py-6 text-gray-800"><%= @property.description %></p>
				<div class="flex justify-between">
					<button class="btn btn-accent">Get Appointment</button>
					<button class="btn btn-neutral">Get additional details</button>
				</div>
			</div>
			<div class="mt-10 flex flex-col items-center justify-between space-y-4 border-t border-b py-4 sm:flex-row sm:space-y-0">
				<div class="flex items-end">
					<h1 class="text-3xl font-bold">$60.50</h1>
					<span class="text-base">/month</span>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/shared/_flash.html.erb
<div class="toast toast-center toast-top">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |type, msg| %>
			<% if type == 'error' || type == 'alert' %>
				<div class='alert bg-red-300 text-black <%= "#{type}" %>' data-controller="toast">
					<span><%= msg %></span>
				</div>
			<% else %>
				<div class="alert alert-success" data-controller="toast">
					<span><%= msg %></span>
				</div>
			<% end %>
    <% end %>
	</div>
</div>

app/views/shared/_flat_alternative.html.erb
<svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#87b689"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M22 22L2 22" stroke="#87b689" stroke-width="1.104" stroke-linecap="round"></path> <path d="M2 11L6.06296 7.74968M22 11L13.8741 4.49931C12.7784 3.62279 11.2216 3.62279 10.1259 4.49931L9.34398 5.12486" stroke="#87b689" stroke-width="1.104" stroke-linecap="round"></path> <path d="M15.5 5.5V3.5C15.5 3.22386 15.7239 3 16 3H18.5C18.7761 3 19 3.22386 19 3.5V8.5" stroke="#87b689" stroke-width="1.104" stroke-linecap="round"></path> <path d="M4 22V9.5" stroke="#87b689" stroke-width="1.104" stroke-linecap="round"></path> <path d="M20 9.5V13.5M20 22V17.5" stroke="#87b689" stroke-width="1.104" stroke-linecap="round"></path> <path d="M15 22V17C15 15.5858 15 14.8787 14.5607 14.4393C14.1213 14 13.4142 14 12 14C10.5858 14 9.87868 14 9.43934 14.4393M9 22V17" stroke="#87b689" stroke-width="1.104" stroke-linecap="round" stroke-linejoin="round"></path> <path d="M14 9.5C14 10.6046 13.1046 11.5 12 11.5C10.8954 11.5 10 10.6046 10 9.5C10 8.39543 10.8954 7.5 12 7.5C13.1046 7.5 14 8.39543 14 9.5Z" stroke="#87b689" stroke-width="1.104"></path> </g></svg>

app/views/shared/_no_image.html.erb
<svg fill="#87b689" viewBox="0 0 32 32" id="icon" xmlns="http://www.w3.org/2000/svg" stroke="#87b689"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><defs><style>.cls-1{fill:none;}</style></defs><title>no-image</title><path d="M30,3.4141,28.5859,2,2,28.5859,3.4141,30l2-2H26a2.0027,2.0027,0,0,0,2-2V5.4141ZM26,26H7.4141l7.7929-7.793,2.3788,2.3787a2,2,0,0,0,2.8284,0L22,19l4,3.9973Zm0-5.8318-2.5858-2.5859a2,2,0,0,0-2.8284,0L19,19.1682l-2.377-2.3771L26,7.4141Z"></path><path d="M6,22V19l5-4.9966,1.3733,1.3733,1.4159-1.416-1.375-1.375a2,2,0,0,0-2.8284,0L6,16.1716V6H22V4H6A2.002,2.002,0,0,0,4,6V22Z"></path><rect id="_Transparent_Rectangle_" data-name="<Transparent Rectangle>" class="cls-1" width="32" height="32"></rect></g></svg>